import { createTheme } from '@vanilla-extract/css';
import {
  borderWidth,
  color,
  duration,
  easing,
  font,
  letterSpacing,
  radius,
  shadow,
  space,
  zIndex,
} from '@touchstone/tokens';
import { vars } from './contract.css.js';

export const darkTheme = createTheme(vars, {
  color: {
    bg: color.neutral[900],
    bgRaised: color.neutral[800],
    bgMuted: color.neutral[700],
    bgOverlay: 'rgba(19, 22, 26, 0.85)',
    bgInput: color.neutral[800],
    bgPage: color.neutral[900],
    fg: color.neutral[50],
    fgMuted: color.neutral[300],
    fgInverse: color.neutral[900],
    fgLink: color.accent[300],
    border: color.neutral[700],
    borderFocus: color.accent[300],
    accent: color.accent[300],
    accentFg: color.neutral[900],
    actionPrimary: color.accent[300],
    actionPrimaryHover: color.accent[100],
    actionSecondary: color.neutral[800],
    actionSecondaryHover: color.neutral[700],
    danger: color.danger[100],
    dangerFg: color.danger[700],
    success: color.success[500],
    warning: '#ffd166',
    info: color.accent[300],
    glow: color.accent[300],
    glowFg: color.neutral[900],
  },
  space,
  radius,
  zIndex,
  shadow,
  borderWidth,
  letterSpacing,
  duration,
  easing,
  font: {
    family: font.family,
    size: font.size,
    weight: font.weight,
    lineHeight: font.lineHeight,
  },
  focus: {
    ringColor: color.accent[300],
    ringWidth: '2px',
    ringOffset: '2px',
  },
});
