import { createTheme } from '@vanilla-extract/css';
import {
  borderWidth,
  color,
  duration,
  easing,
  font,
  letterSpacing,
  radius,
  shadow,
  space,
  zIndex,
} from '@touchstone/tokens';
import { vars } from './contract.css.js';

export const darkTheme = createTheme(vars, {
  color: {
    bg: color.neutral[900],
    bgSolid: color.neutral[900],
    bgRaised: color.neutral[800],
    bgMuted: color.neutral[700],
    bgPanel: color.neutral[800],
    bgOverlay: 'rgba(19, 22, 26, 0.85)',
    bgInput: color.neutral[800],
    bgDisabled: color.neutral[700],
    bgPage: color.neutral[900],
    fg: color.neutral[50],
    fgSecondary: color.neutral[200],
    fgMuted: color.neutral[300],
    fgPlaceholder: color.neutral[500],
    fgDisabled: color.neutral[600],
    fgInverse: color.neutral[900],
    fgLink: color.accent[300],
    border: color.neutral[700],
    borderFocus: color.accent[300],
    borderError: color.danger[500],
    accent: color.accent[300],
    accentFg: color.neutral[900],
    actionPrimary: color.accent[300],
    actionPrimaryHover: color.accent[100],
    actionSecondary: color.neutral[800],
    actionSecondaryHover: color.neutral[700],
    danger: color.danger[100],
    dangerHover: '#fce8e8',
    dangerFg: color.danger[700],
    dangerBg: 'rgba(210, 56, 56, 0.18)',
    success: color.success[500],
    successBg: 'rgba(31, 157, 87, 0.18)',
    warning: '#ffd166',
    warningBg: 'rgba(255, 209, 102, 0.14)',
    info: color.accent[300],
    infoBg: 'rgba(138, 166, 255, 0.16)',
    glow: color.accent[300],
    glowFg: color.neutral[900],
  },
  space,
  radius,
  zIndex,
  shadow,
  borderWidth,
  letterSpacing,
  duration,
  easing,
  font: {
    family: font.family,
    size: font.size,
    weight: font.weight,
    lineHeight: font.lineHeight,
  },
  focus: {
    ringColor: color.accent[300],
    ringWidth: '2px',
    ringOffset: '2px',
  },
});
