import { createTheme } from '@vanilla-extract/css';
import {
  borderWidth,
  color,
  duration,
  easing,
  font,
  letterSpacing,
  radius,
  shadow,
  space,
  zIndex,
} from '@touchstone/tokens';
import { vars } from './contract.css.js';

export const lightTheme = createTheme(vars, {
  color: {
    bg: color.neutral[0],
    bgSolid: color.neutral[0],
    bgRaised: color.neutral[50],
    bgMuted: color.neutral[100],
    bgPanel: color.neutral[50],
    bgOverlay: 'rgba(255, 255, 255, 0.85)',
    bgInput: color.neutral[0],
    bgDisabled: color.neutral[100],
    bgPage: color.neutral[50],
    fg: color.neutral[900],
    fgSecondary: color.neutral[700],
    fgMuted: color.neutral[600],
    fgPlaceholder: color.neutral[400],
    fgDisabled: color.neutral[300],
    fgInverse: color.neutral[0],
    fgLink: color.accent[700],
    border: color.neutral[200],
    borderFocus: color.accent[500],
    borderError: color.danger[500],
    accent: color.accent[500],
    accentFg: color.neutral[0],
    actionPrimary: color.accent[500],
    actionPrimaryHover: color.accent[700],
    actionSecondary: color.neutral[100],
    actionSecondaryHover: color.neutral[200],
    danger: color.danger[500],
    dangerHover: color.danger[700],
    dangerFg: color.neutral[0],
    dangerBg: 'rgba(210, 56, 56, 0.10)',
    success: color.success[500],
    successBg: 'rgba(31, 157, 87, 0.10)',
    warning: '#c08400',
    warningBg: 'rgba(192, 132, 0, 0.12)',
    info: color.accent[500],
    infoBg: 'rgba(58, 102, 255, 0.10)',
    glow: color.accent[500],
    glowFg: color.neutral[0],
  },
  space,
  radius,
  zIndex,
  shadow,
  borderWidth,
  letterSpacing,
  duration,
  easing,
  font: {
    family: font.family,
    size: font.size,
    weight: font.weight,
    lineHeight: font.lineHeight,
  },
  focus: {
    ringColor: color.accent[500],
    ringWidth: '2px',
    ringOffset: '2px',
  },
});
