import type { Meta, StoryObj } from '@storybook/react';
import { Surface } from '@touchstone/atoms';
import { Breadcrumbs } from './Breadcrumbs.js';

const meta = {
  title: 'Molecules/Breadcrumbs',
  component: Breadcrumbs,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Trail of ancestors. Renders as a `<nav>` containing an `<ol>` of ' +
          'items; the visual `/` separator is generated by the recipe between ' +
          'items, so the markup stays one `<li>` per crumb. The last item is ' +
          'marked `current` and renders as page-text with `aria-current="page"` ' +
          "instead of a link.\n\nFills `PageHeader`'s `breadcrumbs` slot, but " +
          'works standalone above any other content.',
      },
    },
  },
  tags: ['autodocs'],
  decorators: [
    (Story) => (
      <Surface
        level="page"
        style={{
          minHeight: '6rem',
          padding: '2rem',
          maxWidth: '960px',
          margin: '0 auto',
        }}
      >
        <Story />
      </Surface>
    ),
  ],
} satisfies Meta<typeof Breadcrumbs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Basic: Story = {
  render: () => (
    <Breadcrumbs>
      <Breadcrumbs.Item asChild>
        <a href="/">workshop</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item asChild>
        <a href="/ledger">ledger</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item current>orders</Breadcrumbs.Item>
    </Breadcrumbs>
  ),
};

export const SingleAncestor: Story = {
  name: 'single ancestor — one step from the root',
  render: () => (
    <Breadcrumbs>
      <Breadcrumbs.Item asChild>
        <a href="/">workshop</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item current>orders</Breadcrumbs.Item>
    </Breadcrumbs>
  ),
};

export const Deep: Story = {
  name: 'deep — five rungs into the ledger',
  render: () => (
    <Breadcrumbs>
      <Breadcrumbs.Item asChild>
        <a href="/">workshop</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item asChild>
        <a href="/ledger">ledger</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item asChild>
        <a href="/ledger/orders">orders</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item asChild>
        <a href="/ledger/orders/2026-04">april</a>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item current>a copper hinge for the lid</Breadcrumbs.Item>
    </Breadcrumbs>
  ),
};

export const CurrentOnly: Story = {
  name: 'current only — the root entry',
  render: () => (
    <Breadcrumbs>
      <Breadcrumbs.Item current>workshop</Breadcrumbs.Item>
    </Breadcrumbs>
  ),
};

export const PlainAncestors: Story = {
  name: 'plain ancestors — no links, just trail',
  render: () => (
    <Breadcrumbs>
      <Breadcrumbs.Item>workshop</Breadcrumbs.Item>
      <Breadcrumbs.Item>ledger</Breadcrumbs.Item>
      <Breadcrumbs.Item current>orders</Breadcrumbs.Item>
    </Breadcrumbs>
  ),
};
