import { cloneElement, forwardRef, isValidElement } from 'react';
import type { ReactElement, ReactNode, Ref } from 'react';
import type { BaseComponentProps } from '@touchstone/atoms';
import * as styles from './Breadcrumbs.css.js';

export interface BreadcrumbsProps extends BaseComponentProps {
  /** Accessible label for the navigation landmark. @default 'breadcrumb' */
  'aria-label'?: string;
  /** Children — typically `Breadcrumbs.Item` rows. */
  children?: ReactNode;
}

/**
 * The trail-of-ancestors row that fills `PageHeader`'s `breadcrumbs` slot
 * (and stands alone above any other content). Renders as `<nav>` containing
 * an `<ol>`; the visual `/` separator is generated by the recipe between
 * items, so the markup stays one `<li>` per crumb. Mark the last item
 * `current` to render it as page-text with `aria-current="page"` instead of
 * a link.
 */
const BreadcrumbsRoot = forwardRef<HTMLElement, BreadcrumbsProps>(function Breadcrumbs(
  { children, 'aria-label': ariaLabel = 'breadcrumb', id, 'data-testid': dataTestId },
  ref,
) {
  return (
    <nav
      ref={ref as Ref<HTMLElement>}
      id={id}
      data-testid={dataTestId}
      aria-label={ariaLabel}
      className={styles.root}
    >
      <ol className={styles.list}>{children}</ol>
    </nav>
  );
});

export interface BreadcrumbsItemProps extends BaseComponentProps {
  /** Mark this item as the current page. Renders as text with `aria-current="page"`. */
  current?: boolean;
  /**
   * Render the immediate child element (typically `<a>` or a router `<Link>`)
   * with the breadcrumb link styling instead of a plain `<span>`. Ignored
   * when `current` is true.
   */
  asChild?: boolean;
  /** Item label. */
  children?: ReactNode;
}

const BreadcrumbsItem = forwardRef<HTMLLIElement, BreadcrumbsItemProps>(function BreadcrumbsItem(
  { current = false, asChild = false, children, id, 'data-testid': dataTestId },
  ref,
) {
  let inner: ReactNode;
  if (current) {
    inner = (
      <span aria-current="page" className={styles.current}>
        {children}
      </span>
    );
  } else if (asChild) {
    if (!isValidElement(children)) return null;
    const child = children as ReactElement<{ className?: string }>;
    inner = cloneElement(child, {
      className: [styles.link, child.props.className].filter(Boolean).join(' '),
    });
  } else {
    inner = <span className={styles.link}>{children}</span>;
  }

  return (
    <li ref={ref} id={id} data-testid={dataTestId} className={styles.item}>
      {inner}
    </li>
  );
});

export const Breadcrumbs = Object.assign(BreadcrumbsRoot, {
  Item: BreadcrumbsItem,
});
