import { create } from '@storybook/theming';

export const storybookThemes = {
  light: create({
    base: 'light',
    brandTitle: 'Touchstone',
    colorPrimary: '#3a66ff',
    colorSecondary: '#3a66ff',
    appBg: '#f7f7f8',
    appContentBg: '#ffffff',
    appPreviewBg: '#ffffff',
    appBorderColor: '#d9dde2',
    appBorderRadius: 6,
    textColor: '#13161a',
    textMutedColor: '#4d555f',
    barBg: '#ffffff',
    barTextColor: '#4d555f',
    barSelectedColor: '#3a66ff',
    inputBg: '#ffffff',
    inputBorder: '#d9dde2',
    inputTextColor: '#13161a',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  dark: create({
    base: 'dark',
    brandTitle: 'Touchstone',
    colorPrimary: '#8aa6ff',
    appBg: '#13161a',
    appContentBg: '#22272d',
    appPreviewBg: '#13161a',
    appBorderColor: '#363c44',
    textColor: '#f7f7f8',
    textMutedColor: '#bfc5cc',
    barBg: '#22272d',
    barSelectedColor: '#8aa6ff',
    inputBg: '#22272d',
    inputBorder: '#363c44',
    inputTextColor: '#f7f7f8',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  synthwave: create({
    base: 'dark',
    brandTitle: 'Touchstone // synthwave',
    colorPrimary: '#ff2d95',
    colorSecondary: '#00fff5',
    appBg: '#0c081c',
    appContentBg: '#16102a',
    appPreviewBg: '#06020f',
    appBorderColor: 'rgba(0, 255, 245, 0.25)',
    appBorderRadius: 6,
    textColor: '#e0d6f6',
    textMutedColor: '#a0c4e8',
    barBg: '#16102a',
    barSelectedColor: '#ff2d95',
    barHoverColor: '#00fff5',
    inputBg: '#0e0e24',
    inputBorder: 'rgba(0, 255, 245, 0.25)',
    inputTextColor: '#e0d6f6',
    fontBase: '"Inter", system-ui, sans-serif',
    fontCode: '"Fira Code", monospace',
  }),
  terminal: create({
    base: 'dark',
    brandTitle: 'Touchstone // terminal',
    colorPrimary: '#33ff33',
    colorSecondary: '#7fff7f',
    appBg: '#0a0a0a',
    appContentBg: '#101410',
    appPreviewBg: '#000000',
    appBorderColor: 'rgba(51, 255, 51, 0.30)',
    appBorderRadius: 0,
    textColor: '#33ff33',
    textMutedColor: '#33ff3399',
    barBg: '#101410',
    barSelectedColor: '#33ff33',
    inputBg: '#0a0a0a',
    inputBorder: 'rgba(51, 255, 51, 0.30)',
    inputTextColor: '#33ff33',
    inputBorderRadius: 0,
    fontBase: '"Fira Code", "JetBrains Mono", ui-monospace, monospace',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
} as const;

export type StorybookThemeName = keyof typeof storybookThemes;

export const resolveStorybookTheme = (name: string | undefined) =>
  name && name in storybookThemes
    ? storybookThemes[name as StorybookThemeName]
    : storybookThemes.light;
