import { create } from '@storybook/theming';

export const storybookThemes = {
  synthwave: create({
    base: 'dark',
    brandTitle: 'Touchstone // synthwave',
    colorPrimary: '#ff2d95',
    colorSecondary: '#00fff5',
    appBg: '#0c081c',
    appContentBg: '#16102a',
    appPreviewBg: '#06020f',
    appBorderColor: 'rgba(0, 255, 245, 0.25)',
    appBorderRadius: 6,
    textColor: '#e0d6f6',
    textMutedColor: '#a0c4e8',
    barBg: '#16102a',
    barSelectedColor: '#ff2d95',
    barHoverColor: '#00fff5',
    inputBg: '#0e0e24',
    inputBorder: 'rgba(0, 255, 245, 0.25)',
    inputTextColor: '#e0d6f6',
    fontBase: '"Inter", system-ui, sans-serif',
    fontCode: '"Fira Code", monospace',
  }),
  terminal: create({
    base: 'dark',
    brandTitle: 'Touchstone // terminal',
    colorPrimary: '#33ff33',
    colorSecondary: '#7fff7f',
    appBg: '#0a0a0a',
    appContentBg: '#101410',
    appPreviewBg: '#000000',
    appBorderColor: 'rgba(51, 255, 51, 0.30)',
    appBorderRadius: 0,
    textColor: '#33ff33',
    textMutedColor: '#33ff3399',
    barBg: '#101410',
    barSelectedColor: '#33ff33',
    inputBg: '#0a0a0a',
    inputBorder: 'rgba(51, 255, 51, 0.30)',
    inputTextColor: '#33ff33',
    inputBorderRadius: 0,
    fontBase: '"Fira Code", "JetBrains Mono", ui-monospace, monospace',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  slate: create({
    base: 'dark',
    brandTitle: 'Touchstone // slate',
    colorPrimary: '#7ba3d4',
    colorSecondary: '#7ba3d4',
    appBg: '#1a1d24',
    appContentBg: '#22262e',
    appPreviewBg: '#1a1d24',
    appBorderColor: '#2a2f38',
    textColor: '#e0e3e8',
    textMutedColor: '#8891a0',
    barBg: '#22262e',
    barSelectedColor: '#7ba3d4',
    inputBg: '#1e2229',
    inputBorder: '#2a2f38',
    inputTextColor: '#e0e3e8',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  'warm-sand': create({
    base: 'dark',
    brandTitle: 'Touchstone // warm sand',
    colorPrimary: '#c0673a',
    colorSecondary: '#c0673a',
    appBg: '#1c1917',
    appContentBg: '#252220',
    appPreviewBg: '#1c1917',
    appBorderColor: '#2e2a27',
    textColor: '#e8e4de',
    textMutedColor: '#9b8f82',
    barBg: '#252220',
    barSelectedColor: '#c0673a',
    inputBg: '#201d1b',
    inputBorder: '#2e2a27',
    inputTextColor: '#e8e4de',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  moss: create({
    base: 'dark',
    brandTitle: 'Touchstone // moss',
    colorPrimary: '#6aad7a',
    colorSecondary: '#6aad7a',
    appBg: '#141a14',
    appContentBg: '#1c231c',
    appPreviewBg: '#141a14',
    appBorderColor: '#243024',
    textColor: '#dce5da',
    textMutedColor: '#7d8b75',
    barBg: '#1c231c',
    barSelectedColor: '#6aad7a',
    inputBg: '#181f18',
    inputBorder: '#243024',
    inputTextColor: '#dce5da',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  coral: create({
    base: 'dark',
    brandTitle: 'Touchstone // coral',
    colorPrimary: '#f08060',
    colorSecondary: '#f08060',
    appBg: '#1f1714',
    appContentBg: '#291f1b',
    appPreviewBg: '#1f1714',
    appBorderColor: '#3a2820',
    textColor: '#f0e0d8',
    textMutedColor: '#a08878',
    barBg: '#291f1b',
    barSelectedColor: '#f08060',
    inputBg: '#241b17',
    inputBorder: '#3a2820',
    inputTextColor: '#f0e0d8',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  pipboy: create({
    base: 'dark',
    brandTitle: 'Touchstone // pip-boy',
    colorPrimary: '#ffb347',
    colorSecondary: '#ffb347',
    appBg: '#0a0a0a',
    appContentBg: '#0f1a0f',
    appPreviewBg: '#0a0a0a',
    appBorderColor: '#1a2e1a',
    textColor: '#33ff33',
    textMutedColor: '#339933',
    barBg: '#0f1a0f',
    barSelectedColor: '#ffb347',
    inputBg: '#0d140d',
    inputBorder: '#1a2e1a',
    inputTextColor: '#33ff33',
    fontBase: '"Fira Code", "JetBrains Mono", ui-monospace, monospace',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  neural: create({
    base: 'dark',
    brandTitle: 'Touchstone // neural',
    colorPrimary: '#38bdf8',
    colorSecondary: '#38bdf8',
    appBg: '#0a0a1a',
    appContentBg: '#12122a',
    appPreviewBg: '#0a0a1a',
    appBorderColor: '#1a1a3a',
    textColor: '#e0e8ff',
    textMutedColor: '#64748b',
    barBg: '#12122a',
    barSelectedColor: '#38bdf8',
    inputBg: '#0e0e22',
    inputBorder: '#1a1a3a',
    inputTextColor: '#e0e8ff',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  blackhole: create({
    base: 'dark',
    brandTitle: 'Touchstone // blackhole',
    colorPrimary: '#a78bfa',
    colorSecondary: '#a78bfa',
    appBg: '#08070d',
    appContentBg: '#110f1a',
    appPreviewBg: '#050508',
    appBorderColor: '#1e1a2e',
    textColor: '#e2dff0',
    textMutedColor: '#9b95b0',
    barBg: '#110f1a',
    barSelectedColor: '#a78bfa',
    inputBg: '#0c0a14',
    inputBorder: '#1e1a2e',
    inputTextColor: '#e2dff0',
    fontBase: 'Inter, system-ui, sans-serif',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
  pacman: create({
    base: 'dark',
    brandTitle: 'Touchstone // pac-man',
    colorPrimary: '#ffff00',
    colorSecondary: '#ffff00',
    appBg: '#000000',
    appContentBg: '#0a0a2a',
    appPreviewBg: '#000000',
    appBorderColor: '#2121de',
    appBorderRadius: 0,
    textColor: '#e0e0e0',
    textMutedColor: '#5555ff',
    barBg: '#0a0a2a',
    barSelectedColor: '#ffff00',
    inputBg: '#0a0a2a',
    inputBorder: '#2121de',
    inputTextColor: '#e0e0e0',
    inputBorderRadius: 0,
    fontBase: '"Fira Code", "JetBrains Mono", ui-monospace, monospace',
    fontCode: '"Fira Code", ui-monospace, monospace',
  }),
} as const;

export type StorybookThemeName = keyof typeof storybookThemes;

export const resolveStorybookTheme = (name: string | undefined) =>
  name && name in storybookThemes
    ? storybookThemes[name as StorybookThemeName]
    : storybookThemes['warm-sand'];
